### ISSUE TITLE
Neo 3 Smart-Contract module update list

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1180]
### Ready to be implemented
_Note: Some issues may have none or more than one proposed solution._

- [ ]  Contract Execution Paid by 3rd party (#1104 / #1147)
- [x]  Simplifying access to transactions and blocks in syscalls (#1081)
- [ ]  NEP-5 template (#973)
- [ ]  Smart Contract inheritance using SysCalls (#772)
- [ ] Read Only Methods (#927)
- [ ] Add contract meta-data to manifest (#1143)
- [ ] Native Naming Contract (#1179)
- [ ] Expand supported cryptography primitives to include industry standards (#972)
- [ ] Auto-generate entry method based on ABI (#1094)

#### To be discussed

- [ ] Abolish Verification Trigger (#1115)
- [ ] Create prefix reserved for system methods (#1097)
- [ ] Invoke contracts' payable method on asset Transfers (#1076)
- [ ] Expand API using Smart Services (#672)

#### Optimization issues
- [ ] Parallel contract validation and execution (#546)
- [ ] Detach state persistence and block persistence (#302)

_This is a work in progress. Please add your comments so we can update the list_

**Comment by lock9** [comment]
@neo-project/core  Hi, can you check this list? Is it ok?
We have some issues open for discussion, if you guys can, please upvote the issues you want to see implemented, this way we can have some initial voting system for the next features.
Thanks

**Comment by shargon** [comment]
> Read Only Methods (#927)

it's done, but we need to agree if it will be implemented ...

**Comment by Tommo-L** [comment]
Could be implemented 


- [ ] Add contract meta-data to manifest (#1143)  
- [ ] Native Naming Contract (#1179)
- [ ] Smart Contract inheritance using SysCalls (#772) 
- [ ] Auto-generate entry method based on ABI (#1094) 
- [ ] Expand supported cryptography primitives to include industry standards (#972)
