### ISSUE TITLE
Neo 3 Opmizations update list

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1189]
### Ready to be implemented
_Note: Some issues may have none or more than one proposed solution._

- [x] Replace `exceptwith` with faster function (#1174)
- [ ] Keep track of sender fee for mempool verification(#1183)
- [x] Auto compression (#710)
- [ ] Batch message (#1088, #1077)
- [ ] Remove duplicate connection (#1123)
- [ ] Send disconnection reason (#1133 #366)
- [ ] opitmize ProtocolHandlerMailbox ( #1201 )  [to be merged]
- [x] Filter unconnected peers in connected list ( #1160 )
- [x] Add GetFullBlocks P2P logic (fix #522  #1138) 
- [ ]  Improve syncing (3x)  ( #899 ) [to be merged]
- [ ]  Store connected peers and try to connect them when restart (#1198) [doing]
- [ ] Don't relay the inventory of block, when block height below remote node's `LastBlockIndex` [to do, waiting for #899]
- [X]  Keep track of sender fee for mempool verification(#1183)
- [X]  opitmize ProtocolHandlerMailbox ( #1201 )
- [X]  Replace exceptwith with faster function (#1174)
- [ ]  Tranasction parallel verifiers (#1228） [to be merged]

#### To be discussed
- [ ] Create performance  metrics (#920)
- [ ] Optimize akka serial execution (#1188)
- [ ] Auxiliary data structure for re-verification (#810)
- [ ] Detached application and verification  (#965 #302)
- [ ] Memory poool opmitization model (#1140 #1148)
- [ ] Avoid bad peers propagation (#1134)
- [ ] Multichannel for Oracles (#1106)
- [ ] Use libp2p (#611)
- [ ] Avoid empty blocks (#921)
- [ ] Adjust block time(dynamic block time) (#375)
- [ ] DBFT3.0 (#1126)
- [ ] Consensus optmization (#519 #426)
- [ ] Improve taskmanager, sync block without header  #522 [waiting for #899 and #1138]
- [x] ~~Transfer transaction directly without `inv` message（no obvious effect）~~
- [ ] Add node health status, better to select peers for communication #542 

_This is a work in progress. Please add your comments so we can update the list_

**Comment by Tommo-L** [comment]
Could you help attach issue #1188 to "Optimize akka serial execution", and recently we will focus on akka's execution.

**Comment by lock9** [comment]
Hi @Tommo-L,  Do you mean pin the issue or add it here?

**Comment by Tommo-L** [comment]
add it here, like "Optimize akka serial execution(#1188)"

**Comment by Tommo-L** [comment]
p2p module

add to be implemented:
- [ ] Filter unconnected peers in connected list ( #1160 ) [to be merged]
- [ ] Add GetFullBlocks P2P logic (fix #522  #1138) [to be merged]
- [ ]  Improve syncing (3x)  ( #899 ) [to be merged]
- [ ]  Store connected peers and try to connect them when restart (#1198) [doing]
- [ ] Don't relay the inventory of block, when block height below remote node's `LastBlockIndex` [to do]

Add to be discussed
- [ ] Improve taskmanager, sync block without header  #522
- [ ] Transfer transaction directly without `inv` message 
- [ ] Add node health status, better to select peers for communication #542

**Comment by Tommo-L** [comment]
hi @lock9 , could you help update the following item
- [x] Replace exceptwith with faster function (#1174)

**Comment by Tommo-L** [comment]
increase tps 
- [X]  Keep track of sender fee for mempool verification(#1183)
- [X]  opitmize ProtocolHandlerMailbox ( #1201 )
- [X]  Replace exceptwith with faster function (#1174)
- [ ]  Tranasction parallel verifiers (#1128） [to be merged]
