### ISSUE TITLE
Preview4 Checklist

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1936]
### Neo3-preview4 Release Checklist

Now We're preparing the checklist of neo3-preview4 for task collection.  We've already focused on these issues and PRs but we're also glad to collect other requirements. This checklist will be frozen on **Dec 7th**, then we'll work on these.
This release should be on **12/15 2020** (Can be moved forward if completed ahead). Then Preview4 testnet will be launched. And two weeks later, we will release neo-cli v3.0.0 and launch neo3 testnet. Formal testnet will nearly the same as Preview4 testnet, but chain data and seed nodes will be reset. Now we're focusing on these issues and PRs.

**Since more PRs and Issues are coming to Checklist, we delay the release time for three weeks(12/15 2020)**

**Mandatory issues**

- [x] Redefine opcode prices https://github.com/neo-project/neo/issues/1875
~how to sign state root message https://github.com/neo-project/neo/issues/1526~ (**will be fixed after Preview4**)
- [x] Update TransactionManager to support magic parameter https://github.com/neo-project/neo-modules/issues/343
- [x] `OnPersist` and `PostPersist` have the same application log hash https://github.com/neo-project/neo-modules/issues/354
- [x] Remove sender from invoke* RPCs https://github.com/neo-project/neo-modules/issues/351
- [x] Encode scripts in base64 https://github.com/neo-project/neo-modules/issues/337
- [x] Expand getversion RPC call output with network's magic number https://github.com/neo-project/neo-modules/issues/358
~REQ: RPC call with Verification trigger type https://github.com/neo-project/neo/issues/1977~ (**will be fixed after Preview4**)
- [x] Return FaultException for invokefunction and invokescript RPC calls https://github.com/neo-project/neo-modules/issues/334
- [x] validateaddress should not accept hexs, or should it? https://github.com/neo-project/neo-modules/issues/352
- [x] Non-asset signer in invokefunction should not be able to create tx automatically and should not be in the list of signers. https://github.com/neo-project/neo-modules/issues/370
- [x] neo-cli isn't able to show exception msg from Smart Contract but just show Error https://github.com/neo-project/neo-node/issues/672 
- [x] Redefine Opcode/Syscall price https://github.com/neo-project/neo/issues/2004
- [x] Querying contracts by ID/name, server side https://github.com/neo-project/neo-modules/issues/355
- [x] Keep the hash unchanged when upgrading contracts https://github.com/neo-project/neo/issues/2021

**Mandatory PRs**

- [x] Add incentive for voter https://github.com/neo-project/neo/pull/1848
- [x] Add incentive for committee https://github.com/neo-project/neo/pull/1847
- [x] Add incentive for NEO holder https://github.com/neo-project/neo/pull/1845
- [x] Recalculate committee every 28 blocks https://github.com/neo-project/neo/pull/1907
- [x] Asynchronous oracle https://github.com/neo-project/neo/pull/1738
- [x] Add UInt160, UInt256 and ECPoint to SmartContract Framework https://github.com/neo-project/neo-devpack-dotnet/pull/362
~Oracle plugin https://github.com/neo-project/neo-modules/pull/326~
~Allow oracle to access NeoFS~
- [x] Compiler support for asynchronous oracle https://github.com/neo-project/neo-devpack-dotnet/pull/337
- [x] Add GetCommittee RPC method https://github.com/neo-project/neo-modules/pull/342
- [x] Update dependencies https://github.com/neo-project/neo-modules/pull/338
- [x] Pure async RpcClient https://github.com/neo-project/neo-modules/pull/335
- [x] Remove sender from invoke method https://github.com/neo-project/neo-modules/pull/368
- [x] invoke* use base64 script https://github.com/neo-project/neo-modules/pull/362
- [x] Add `magic` field in getversion https://github.com/neo-project/neo-modules/pull/363
- [x] Add `exception` field in invokeresult https://github.com/neo-project/neo-modules/pull/364
- [x] Fix validateaddress https://github.com/neo-project/neo-modules/pull/365
- [x] Update contract without change the hash https://github.com/neo-project/neo/pull/2044
- [x] Fix native serialize https://github.com/neo-project/neo/pull/1988
- [x] Keeping up to date with neo: trigger type https://github.com/neo-project/neo-modules/pull/380
- [x] Fix sync issue https://github.com/neo-project/neo/pull/2031
~Fix GAS initialize https://github.com/neo-project/neo/pull/2006~ (**will be fixed in v3.0.0 due to the total amount of that time**)
~Optimize gas storage https://github.com/neo-project/neo/pull/1987~ (**will be fixed after Preview4**)
~Add Fee Ratio https://github.com/neo-project/neo/pull/2032~
- [x] Fixed some opcode price https://github.com/neo-project/neo/pull/2020
- [x] Make BinarySerializer public https://github.com/neo-project/neo/pull/2041
- [x] Sync neo changes https://github.com/neo-project/neo-devpack-dotnet/pull/391
- [x] Implement NEP-17 https://github.com/neo-project/neo/pull/2024
- [x] Update RpcServer.SmartContract.cs https://github.com/neo-project/neo-modules/pull/400
- [x] Update LogReader.cs https://github.com/neo-project/neo-modules/pull/401
- [x] SmartContract/Native: implement adjustable opcode pricing https://github.com/neo-project/neo/pull/2045
- [x] Centralize _initialize call https://github.com/neo-project/neo/pull/2052
- [x] Create ManagementContract https://github.com/neo-project/neo/pull/2119
- [x] Sync update with neo pull 2119 https://github.com/neo-project/neo-devpack-dotnet/pull/402
- [x] Sync to management SC https://github.com/neo-project/neo-node/pull/689
- [x] Sync to management SC https://github.com/neo-project/neo-modules/pull/418
@neo-project/developers @neo-project/core @neo-project/ngd-seattle

**Comment by devhawk** [comment]
Can we include #335 plus a fix for #343 in preview 4? Once #335 is in, I can do the work to fix #343 very quickly.

**Comment by vncoelho** [comment]
I agree, @devhawk, if you need any support let me know.

**Comment by vncoelho** [comment]
Who will proceed with "Allow oracle to access NeoFS", @roman-khimov @neo-project/ngd-shanghai? It will probably after we merge https://github.com/neo-project/neo-modules/pull/326?

**Comment by Tommo-L** [comment]
> Who will proceed with "Allow oracle to access NeoFS", @roman-khimov @neo-project/ngd-shanghai? The template for the asynchronous has been merged. Will it come after we merge [neo-project/neo-modules#326](https://github.com/neo-project/neo-modules/pull/326) or you are already preparing it?

We'll add this feature after https://github.com/neo-project/neo-modules/pull/326 merged.

**Comment by devhawk** [comment]
> I agree with those two PRs, @devhawk, if you need any support let me know.

FYI @vncoelho I had linked to the wrong PRs - the ones I was mentioning are in modules repo

**Comment by vncoelho** [comment]
Then I need to double check...aehuahuea The async RPC looks good in my opinion but not necessarily a feature that we need right now. But if you have in mind a good way to distribute its loads it would be good if it can come asap.

**Comment by devhawk** [comment]
> Then I need to double check...aehuahuea The async RPC looks good in my opinion but not necessarily a feature that we need right now. But if you have in mind a good way to distribute its loads it would be good if it can come asap.

You might not need it, but neo express does.

**Comment by vncoelho** [comment]
If it is a requirement perhaps it should be included.

**Comment by devhawk** [comment]
We should have a simple Oracles sample for preview 4 developers

**Comment by devhawk** [comment]
Can we include https://github.com/neo-project/neo-devpack-dotnet/pull/362 in checklist for preview 4?

**Comment by superboyiii** [comment]
> Can we include [neo-project/neo-modules#335](https://github.com/neo-project/neo-modules/pull/335) plus a fix for [neo-project/neo-modules#343](https://github.com/neo-project/neo-modules/issues/343) in preview 4? Once 335 PR is in, I can do the work to fix 343 very quickly.

Done.

**Comment by superboyiii** [comment]
> Can we include [neo-project/neo-devpack-dotnet#362](https://github.com/neo-project/neo-devpack-dotnet/pull/362) in checklist for preview 4?

Done.

**Comment by devhawk** [comment]
FYI @superboyiii I added the fix for  neo-project/neo-modules#343 to neo-project/neo-modules#335

**Comment by roman-khimov** [comment]
IIUC preview4 is supposed to have broader support from various community projects, especially ones that are more developer- and user-oriented, like compilers, wallets, light nodes and alike. These tend to care more about external interfaces provided by the node rather than internal improvements, thus I'd like to raise priority for some of the issues related to these external node interfaces.

neo-project/neo-modules#354 --- this one is a MUST before preview4 to me
neo-project/neo-modules#351, neo-project/neo-modules#337 --- affecting frequently used APIs, better deal with them now than leave post-preview4
neo-project/neo-modules#358, neo-project/neo-modules#355, neo-project/neo#1977 --- these are very important for some RPC clients
neo-project/neo-modules#334 --- minor, but easy to fix and helps a lot
neo-project/neo-modules#352 --- minor, but easy to fix

**Comment by superboyiii** [comment]
> IIUC preview4 is supposed to have broader support from various community projects, especially ones that are more developer- and user-oriented, like compilers, wallets, light nodes and alike. These tend to care more about external interfaces provided by the node rather than internal improvements, thus I'd like to raise priority for some of the issues related to these external node interfaces.
> 
> [neo-project/neo-modules#354](https://github.com/neo-project/neo-modules/issues/354) --- this one is a MUST before preview4 to me
> [neo-project/neo-modules#351](https://github.com/neo-project/neo-modules/issues/351), [neo-project/neo-modules#337](https://github.com/neo-project/neo-modules/issues/337) --- affecting frequently used APIs, better deal with them now than leave post-preview4
> [neo-project/neo-modules#358](https://github.com/neo-project/neo-modules/issues/358), [neo-project/neo-modules#355](https://github.com/neo-project/neo-modules/issues/355), #1977 --- these are very important for some RPC clients
> [neo-project/neo-modules#334](https://github.com/neo-project/neo-modules/issues/334) --- minor, but easy to fix and helps a lot
> [neo-project/neo-modules#352](https://github.com/neo-project/neo-modules/issues/352) --- minor, but easy to fix

All these are added.

**Comment by Tommo-L** [comment]
Add https://github.com/neo-project/neo/pull/1973, as it's imcompatible.

**Comment by superboyiii** [comment]
> Add #1973, as it's imcompatible.

Done.

**Comment by devhawk** [comment]
Any chance of including #1966 in preview 4?

**Comment by devhawk** [comment]
Is preview 4 the last chance for breaking changes? i.e. will we be able to consider making more changes for #1866 after preview 4? (such as #1952 and https://github.com/neo-project/neo-devpack-dotnet/pull/371)

**Comment by superboyiii** [comment]
> Any chance of including #1966 in preview 4?

Sorry, Harry. This PR is excellent but it has made huge changes, maybe we could merge it to neo-core after neo v3.0.0 released and review it step by step. 

> Is preview 4 the last chance for breaking changes? i.e. will we be able to consider making more changes for #1866 after preview 4? (such as #1952 and neo-project/neo-devpack-dotnet#371)
We could take it into neo-core between preivew4 and neo v3.0.0.

**Comment by roman-khimov** [comment]
> All these are added.

Hmm, I don't see neo-project/neo-modules#355 there, any particular reason for that?

**Comment by devhawk** [comment]
> > Any chance of including #1966 in preview 4?
> 
> Sorry, Harry. This PR is excellent but it has made huge changes, maybe we could merge it to neo-core after neo v3.0.0 released and review it step by step.
>
> > Is preview 4 the last chance for breaking changes? i.e. will we be able to consider making more changes for #1866 after preview 4? (such as #1952 and [neo-project/neo-devpack-dotnet#371](https://github.com/neo-project/neo-devpack-dotnet/pull/371))
> 
> We could take it into neo-core between preivew4 and neo v3.0.0.

#1966 has changes related to #1866 (i.e. domain model unification) and #1865 (domain model decoupling). I'm much more concerned about getting changes related to unification in before shipping v3 than decoupling. Can we do a post preview 4 PR to move types like Block and Transaction to the Neo.Models namespace?

**Comment by superboyiii** [comment]
> > > Any chance of including #1966 in preview 4?
> > 
> > 
> > Sorry, Harry. This PR is excellent but it has made huge changes, maybe we could merge it to neo-core after neo v3.0.0 released and review it step by step.
> > > Is preview 4 the last chance for breaking changes? i.e. will we be able to consider making more changes for #1866 after preview 4? (such as #1952 and [neo-project/neo-devpack-dotnet#371](https://github.com/neo-project/neo-devpack-dotnet/pull/371))
> > 
> > 
> > We could take it into neo-core between preivew4 and neo v3.0.0.
> 
> #1966 has changes related to #1866 (i.e. domain model unification) and #1865 (domain model decoupling). I'm much more concerned about getting changes related to unification in before shipping v3 than decoupling. Can we do a post preview 4 PR to move types like Block and Transaction to the Neo.Models namespace?

@shargon @erikzhang  What's your opinion?

**Comment by superboyiii** [comment]
> > All these are added.
> 
> Hmm, I don't see [neo-project/neo-modules#355](https://github.com/neo-project/neo-modules/issues/355) there, any particular reason for that?

A mis, add it back now.

**Comment by devhawk** [comment]
https://github.com/neo-project/neo/pull/2041 is quite simple (makes BinarySerializer class public). Can we include this in preview 4?

**Comment by superboyiii** [comment]
> #2041 is quite simple (makes BinarySerializer class public). Can we include this in preview 4?

Sure.

**Comment by devhawk** [comment]
@superboyiii I believe https://github.com/neo-project/neo-modules/issues/385 is a must fix for preview 4. Invoke script RPC method script parameter handling doesn't match between RpcClient and RpcServer

**Comment by superboyiii** [comment]
> @superboyiii I believe [neo-project/neo-modules#385](https://github.com/neo-project/neo-modules/issues/385) is a must fix for preview 4. Invoke script RPC method script parameter handling doesn't match between RpcClient and RpcServer

Fixed in https://github.com/neo-project/neo-modules/pull/386

**Comment by devhawk** [comment]
Are we switching to net5.0 target framework across the whole neo project? If we make that [switch in Neo.VM](https://github.com/neo-project/neo-vm/commit/cf620066018deb01a9420e870999c1af53307984) does that mean all downstream projects have to switch as well?

**Comment by shargon** [comment]
I think that is not for preview 4

**Comment by devhawk** [comment]
> > Are we switching to net5.0 target framework across the whole neo project?
> 
> I think that is not for preview 4

the net5.0 change has already been made in neo-vm project. So is the plan to create a preview 4 fork at the commit before the change was made?

**Comment by devhawk** [comment]
I think this needs to be fixed for preview 4: https://github.com/neo-project/neo/issues/2072

**Comment by Tommo-L** [comment]
I think we'd better review and merge this two incompatible PRs first.  https://github.com/neo-project/neo/pull/2044/ https://github.com/neo-project/neo/pull/2056/

**Comment by ProDog** [comment]
> I think we'd better review and merge this two incompatible PRs first. #2044 #2056

https://github.com/neo-project/neo/pull/2044 need https://github.com/neo-project/neo-devpack-dotnet/pull/388 and https://github.com/neo-project/neo-devpack-dotnet/pull/391, I think we can review and merge it as soon as possible, then test it together.

**Comment by shargon** [comment]
https://github.com/neo-project/neo-devpack-dotnet/pull/388 will be replaced by https://github.com/neo-project/neo-devpack-dotnet/pull/391

**Comment by devhawk** [comment]
https://github.com/neo-project/neo/issues/2085 looks like another issue that needs to be fixed for preview 4, but given the in-flight state of some of the NEP-17 related stuff, a fix for this might already be waiting to merge.

**Comment by lock9** [comment]
Hello,
There are a few items not checked on this list. Is the release date going to be postponed?

**Comment by devhawk** [comment]
I hate to add to this list, but #2151 needs to be fixed for preview 4.

**Comment by kelimelogg** [comment]
is it delayed again? adverse situation for the investor

**Comment by lock9** [comment]
@kelimelogg There are always some delays on software projects, but you shouldn't worry, they are delaying it because they want to make it right. It is a healthy delay.

![image](https://user-images.githubusercontent.com/38396062/102378836-fa369680-3fa4-11eb-93c1-d344a2ccf2ac.png)

**Comment by PsychedelicHell** [comment]
Please release Neo3 so I can sell.

**Comment by kelimelogg** [comment]
what else is expected?
