### ISSUE TITLE
Preview5 Checklist

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2171]
Now We're preparing the checklist of neo3-preview5 for task collection.  Since still much new features are not included in preview4 (.Net 5, Oracle, State Service, etc), we plan to make preview5 out as the final preview version. This checklist will be frozen on **1/19 2021**, then we'll work on these. This release should be on **2/3 2021** . One month later, Formal testnet will be launched (At the middle of March). Formal testnet will nearly the same as Preview5 testnet, but chain data and seed nodes will be reset. Now we're focusing on these issues and PRs but we're also glad to collect other requirements.

**PS: Recommend to complete any incompatible or core features into this version, others needn't to be so hurry. (Not much time left for release)**

**Mandatory issues**

- [x] RpcServer: partial Signers unmarshalling https://github.com/neo-project/neo-modules/issues/423
- [x] All rpcserver are not working https://github.com/neo-project/neo-modules/issues/440
- [x] deployed contract name support in getContractState https://github.com/neo-project/neo-modules/issues/426 (Now available in Native Contract)
- [x] What will happen if 4 of the 7 elected consensus nodes are offline? https://github.com/neo-project/neo/issues/2203 (Need further discussion, will not included in Preview5)

**Mandatory PRs**

- [x] Remove Concat APIs https://github.com/neo-project/neo/pull/2170
- [x] Add System.Storage.FindKeys https://github.com/neo-project/neo/pull/2169
- [x] Remove Callback APIs https://github.com/neo-project/neo/pull/2168
- [x] Dynamic Call https://github.com/neo-project/neo/pull/2167
~Add callt price https://github.com/neo-project/neo/pull/2162~
- [x] Reserve 4 bytes for NefFile https://github.com/neo-project/neo/pull/2160
- [x] [StateService] Storage https://github.com/neo-project/neo-modules/pull/431
- [x] dotnet 5.0 https://github.com/neo-project/neo-modules/pull/407
- [x] OracleService https://github.com/neo-project/neo-modules/pull/326
- [x] Neo Name Service https://github.com/neo-project/neo/pull/2201
- [x] dotnet 5.0 https://github.com/neo-project/neo-node/pull/681
~Downgrade dependency https://github.com/neo-project/neo/pull/2178~
- [x] Fix dotnet5 https://github.com/neo-project/neo-modules/pull/442
- [x] Sync neo-core https://github.com/neo-project/neo-devpack-dotnet/pull/414
- [x] Fix UT https://github.com/neo-project/neo-modules/pull/454
- [x] Create consensus plugin https://github.com/neo-project/neo-modules/pull/453
- [x] Use CALLT https://github.com/neo-project/neo-devpack-dotnet/pull/420
- [x] Update vm https://github.com/neo-project/neo/pull/2225
- [x] Sync with neo https://github.com/neo-project/neo-modules/pull/465
- [x] Change smart contract hash computation https://github.com/neo-project/neo/pull/2240
- [x] Add overloads on ContractManagement  https://github.com/neo-project/neo/pull/2242
- [x] Change smart contract hash computation https://github.com/neo-project/neo-devpack-dotnet/pull/438
- [x] update oracleservice wallet https://github.com/neo-project/neo-modules/pull/473
- [x] Move everything into LedgerContract  https://github.com/neo-project/neo/pull/2215
- [x] Sync with neo pr2215(LedgerContract) https://github.com/neo-project/neo-node/pull/720
- [x] Sync with neo LedgerContract https://github.com/neo-project/neo-modules/pull/471
- [x] Change ContractManifest serialization https://github.com/neo-project/neo/pull/2254

**State root 3 steps**
- [x] [StateService] Storage and P2P https://github.com/neo-project/neo-modules/pull/431
- [x] [StateService] Validation https://github.com/neo-project/neo-modules/pull/470
- [x] [StateService] More command & RPC https://github.com/neo-project/neo-modules/pull/475
- [x]  Add header back https://github.com/neo-project/neo/pull/2259
- [x] Add test mode gas when invoking https://github.com/neo-project/neo-node/pull/727
- [x] fix broadcast getheaders https://github.com/neo-project/neo-node/pull/730
- [x] Add pending signature to ProcessInvokeWithWallet https://github.com/neo-project/neo-modules/pull/490

@neo-project/developers @neo-project/core @neo-project/ngd-seattle

**Comment by p7510543** [comment]
You may meant 2021 not 2020

**Comment by PazBazak** [comment]
Why you guys updating this once in 2 weeks or so... 2/3 of the issues are closed for days now... The community following this, please check the closed issues and merged PR. Update this issue more frequently:D

**Comment by superboyiii** [comment]
> Why you guys updating this once in 2 weeks or so... 2/3 of the issues are closed for days now... The community following this, please check the closed issues and merged PR. Update this issue more frequently:D

Thanks. Done.

**Comment by cloud8little** [comment]
Oracle/CALLT/update vm was merged. please update the items.

**Comment by gsmachado** [comment]
I think that investigating and fixing this one, it's important as well: https://github.com/neo-project/neo/issues/2275

**Comment by superboyiii** [comment]
https://github.com/neo-project/neo-node/releases/tag/v3.0.0-preview5
