### ISSUE TITLE
RC1 Checklist

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2329]
Now We're preparing the checklist of neo v3.0.0-RC1 (formal testnet) for task collection.  For formal testnet, all versions should be compatible. We plan to release mainnet around **June** so that we may iterate 2 or 3 testnet versions until it's stable enough. This checklist will be frozen on **3/5 2021**, then we'll work on these. This release will be on **3/16 2021** and testnet will be set up on  **3/25 2021**. Now we're focusing on these issues and PRs but we're also glad to collect other requirements.

**Mandatory issues**

~Emergency mode issues https://github.com/neo-project/neo/issues/2203~ (No excellent solution yet, will not be solved in RC1)

**Mandatory PRs**

- [x] Allow reverify inventories https://github.com/neo-project/neo/pull/2326
- [x] Allow plugins work with multipe NeoSystems https://github.com/neo-project/neo/pull/2323
- [x] Modify CallStates https://github.com/neo-project/neo/pull/2317 (Closed)
- [x] Fix CallFlags for native contracts and syscalls https://github.com/neo-project/neo/pull/2339
- [x] Remove some settings from policy contract https://github.com/neo-project/neo/pull/2300
- [x] Integrate NeoFS into oracle module (NeoFS API) https://github.com/neo-project/neo-modules/pull/518
- [x] Add tx count check on prepare request https://github.com/neo-project/neo-modules/pull/516 (Closed)
- [x] Sync neo https://github.com/neo-project/neo-modules/pull/517
- [x] Update OracleService.cs https://github.com/neo-project/neo-modules/pull/535
- [x] Make CallFromNativeContract debuggable https://github.com/neo-project/neo/pull/2358
- [x] Allow native contracts to be disabled on private net https://github.com/neo-project/neo/pull/2361
- [x] Fix Header's hash https://github.com/neo-project/neo/pull/2367
- [x] fix dead lock with state service https://github.com/neo-project/neo/pull/2368
- [x] Add GetSignatures to ContractParametersContext https://github.com/neo-project/neo/pull/2370
- [x] Fix CalculateNetworkFee https://github.com/neo-project/neo/pull/2375
- [x] Load settings from IConfigurationSection https://github.com/neo-project/neo/pull/2376
- [x] Move AES methods and mark them as private https://github.com/neo-project/neo/pull/2360
- [x] Add GetSignatures to ContractParametersContext https://github.com/neo-project/neo/pull/2370
- [x] Combine config.json and protocol.json https://github.com/neo-project/neo-node/pull/753
- [x] Role: add NeoFS alphabet node role https://github.com/neo-project/neo/pull/2377
- [x] public RpcServerSettings https://github.com/neo-project/neo-modules/pull/539
- [x]  CreateGenesisBlock https://github.com/neo-project/neo/pull/2381
- [x] add helper OnSysCall for use in blockchain toolkit https://github.com/neo-project/neo/pull/2378 (Closed)
- [x] Fix Blockchain initialization https://github.com/neo-project/neo/pull/2397
- [x] get localnode after start https://github.com/neo-project/neo-node/pull/758
- [x] Generate manifest with static calls https://github.com/neo-project/neo-devpack-dotnet/pull/478
- [x] [Oracle] Optimize neofs return type https://github.com/neo-project/neo-modules/pull/554

@neo-project/developers @neo-project/core @neo-project/ngd-seattle

**Comment by ioannistsil** [comment]
so testnet will be released on 3/22?

**Comment by shargon** [comment]
It's better to pin the issue https://github.com/neo-project/neo/issues/2316 instead of https://github.com/neo-project/neo/pull/2317

**Comment by steven1227** [comment]
> so testnet will be released on 3/22?

It is an estimated time. We will announce all the community and developers when it launch.

**Comment by cloud8little** [comment]
better to add #2357

**Comment by nitinmb** [comment]
Neo community is actively following this . 
Can we please do regular updates to this checklist ? There seem to be many issues /prs which are already closed/merged. - thanks

**Comment by superboyiii** [comment]
> Neo community is actively following this .
> Can we please do regular updates to this checklist ? There seem to be many issues /prs which are already closed/merged. - thanks

Thanks. Done.

**Comment by nitinmb** [comment]
@superboyiii  - thank you, appreciate it !!

**Comment by roman-khimov** [comment]
#2345, please.

**Comment by ioannistsil** [comment]
hello @superboyiii could you update the list

**Comment by superboyiii** [comment]
> hello @superboyiii could you update the list

Done

**Comment by RAJENDRA4545** [comment]
When testnet 
Can you provide any specific date ?

**Comment by superboyiii** [comment]
> When testnet
> Can you provide any specific date ?

03/15 -> release
03/16 -> testnet

**Comment by RAJENDRA4545** [comment]
> > When testnet
> 
> > Can you provide any specific date ?
> 
> 
> 
> 03/15 -> release
> 
> 03/16 -> testnet

When official announcement 
?

**Comment by devhawk** [comment]
@superboyiii Can we add #2378 to the list?

**Comment by devhawk** [comment]
@superboyiii Also need to add https://github.com/neo-project/neo-modules/pull/539 to the list. Blockchain Toolkit can NOT work around this one

**Comment by superboyiii** [comment]
> @superboyiii Also need to add [neo-project/neo-modules#539](https://github.com/neo-project/neo-modules/pull/539) to the list. Blockchain Toolkit can NOT work around this one

All done.

**Comment by RAJENDRA4545** [comment]
When official announcement?

**Comment by RAJENDRA4545** [comment]
When official announcement about testnet ?

**Comment by devhawk** [comment]
@superboyiii #2381 is a "nice-to-have" for RC1. I think it's important there is a single source of logic for creating the genesis block, so I'd rather not duplicate that logic in blockchain toolkit (but can copy the code for RC1)

**Comment by superboyiii** [comment]
> @superboyiii #2381 is a "nice-to-have" for RC1. I think it's important there is a single source of logic for creating the genesis block, so I'd rather not duplicate that logic in blockchain toolkit (but can copy the code for RC1)

I've added it to the list but not sure if it can be merged into RC1 timely since not time left before release.

**Comment by devhawk** [comment]
> I've added it to the list but not sure if it can be merged into RC1 timely since not time left before release.

I understand. Not critical for RC1

**Comment by devhawk** [comment]
Note, I think I can work around #2388 for neo-express, but other folks will have issues deploying contracts if the network fee is calculated incorrectly

**Comment by ioannistsil** [comment]
when testnet annoucment

**Comment by RAJENDRA4545** [comment]
Is there anyone to respond 
When testnet?

**Comment by superboyiii** [comment]
> Is there anyone to respond
> When testnet?

We will release node today and set up testnet on 3/18. Official announcement will come soon.

**Comment by superboyiii** [comment]
> when testnet annoucment

We will release node today and set up testnet on 3/18. Official announcement will come soon.

**Comment by RAJENDRA4545** [comment]
Why date changed from 3/16 to 3/18 
Admin can you explain 
And still no announcement

**Comment by RAJENDRA4545** [comment]
There is any link 
Where we can track testnet 
Admin ?

**Comment by RAJENDRA4545** [comment]
> > Is there anyone to respond
> 
> > When testnet?
> 
> 
> 
> We will release node today and set up testnet on 3/18. Official announcement will come soon.

No update on testnet 
Did you released node ?

**Comment by devhawk** [comment]
@superboyiii https://github.com/neo-project/neo-modules/pull/563

**Comment by neocactus3** [comment]
> > > Is there anyone to respond
> > 
> > 
> > > When testnet?
> > 
> > 
> > We will release node today and set up testnet on 3/18. Official announcement will come soon.
> 
> No update on testnet
> Did you released node ?

Seems like you are super excited about the TestNet - we all are!  Let's give the Devs the latitude to push this thing out. They are working hard. They will communicate when it's ready.

**Comment by RAJENDRA4545** [comment]
> > > > Is there anyone to respond
> 
> > > 
> 
> > > 
> 
> > > > When testnet?
> 
> > > 
> 
> > > 
> 
> > > We will release node today and set up testnet on 3/18. Official announcement will come soon.
> 
> > 
> 
> > No update on testnet
> 
> > Did you released node ?
> 
> 
> 
> Seems like you are super excited about the TestNet - we all are!  Let's give the Devs the latitude to push this thing out. They are working hard. They will communicate when it's ready. 

Not an single official announcement 
What about promotions 
?

**Comment by Newfknbie420** [comment]
> > > > > Is there anyone to respond
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > When testnet?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > We will release node today and set up testnet on 3/18. Official announcement will come soon.
> > 
> > 
> > > 
> > 
> > 
> > > No update on testnet
> > 
> > 
> > > Did you released node ?
> > 
> > 
> > Seems like you are super excited about the TestNet - we all are!  Let's give the Devs the latitude to push this thing out. They are working hard. They will communicate when it's ready.
> 
> Not an single official announcement
> What about promotions
> ?

Stop asking dump questions, this is working space and you have done nothing to improve their works.

**Comment by cryptodelboy** [comment]
> > > > > Is there anyone to respond
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > When testnet?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > We will release node today and set up testnet on 3/18. Official announcement will come soon.
> > 
> > 
> > > 
> > 
> > 
> > > No update on testnet
> > 
> > 
> > > Did you released node ?
> > 
> > 
> > Seems like you are super excited about the TestNet - we all are!  Let's give the Devs the latitude to push this thing out. They are working hard. They will communicate when it's ready.
> 
> Not an single official announcement
> What about promotions
> ?

Can you please stop spamming their workspace? Team is working hard to deliver everything on time. Your constant spamming will not help in any way. Please use telegram, discord or twitter if you have any doubts about your investment, but dont turn this space into When moon questions to earn few $ on the testnet announcement.

**Comment by ioannistsil** [comment]
finally #478 merged

**Comment by superboyiii** [comment]
https://github.com/neo-project/neo-node/releases/tag/v3.0.0-rc1
