### ISSUE TITLE
RC2 Checklist

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2418]
Now We're preparing the checklist of neo v3.0.0-RC2 for task collection. We plan to release mainnet around **June** and RC2 might be the last RC version. This checklist will be frozen around **the middle of April**, then we'll work on these. This release will be around **the end of April**. RC2 testnet will be set up on **the middle of May**. Now we're focusing on these issues and PRs but we're also glad to collect other requirements.

**Mandatory issues**

- [x] Allow to use invocation script for contract-based witness verification inside CalculateNetworkFee method https://github.com/neo-project/neo/issues/2412
~~Network assistance for multisignature transaction forming https://github.com/neo-project/neo/issues/1573~~ (will be solve in RC3)

**Mandatory PRs**

- [x] remaining magic to network https://github.com/neo-project/neo/pull/2417
- [x] Neo.Compiler.CSharp https://github.com/neo-project/neo-devpack-dotnet/pull/482
- [x] Allow to use invocation script for contract-based witness verification inside CalculateNetworkFee method https://github.com/neo-project/neo/pull/2414
~~Add notary contract https://github.com/neo-project/neo/pull/2425~~ (will be in RC3)
~~Neofs https://github.com/neo-project/neo-modules/pull/582~~ (will be in RC3)
- [x] Add update https://github.com/neo-project/neo-node/pull/771
- [x] Support JSONPath https://github.com/neo-project/neo/pull/2446

@neo-project/developers @neo-project/core @neo-project/ngd-seattle

**Comment by bankotsu007** [comment]
Good luck!

**Comment by vncoelho** [comment]
Very good @superboyiii, count with us for testing NeoFS C# integrated with our system!

**Comment by nitinmb** [comment]
@superboyiii  - Could you please update the status on RC2 checklist if anything changed ?

**Comment by superboyiii** [comment]
> @superboyiii - Could you please update the status of RC2 checklist if anything changed ?

Sure

**Comment by Ethour** [comment]
Any update on RC2 launch date?

**Comment by superboyiii** [comment]
RC2 is released. See https://github.com/neo-project/neo-node/releases/tag/v3.0.0-rc2. RC2 testnet will be set up on May 18th.

**Comment by ioannistsil** [comment]
> RC2 is released. See https://github.com/neo-project/neo-node/releases/tag/v3.0.0-rc2. RC2 testnet will be set up on May 18th.

is that the final or we will see RC3?

**Comment by eminmtas** [comment]
Excited to see mainnet 3.0 launch!

**Comment by superboyiii** [comment]
> > RC2 is released. See https://github.com/neo-project/neo-node/releases/tag/v3.0.0-rc2. RC2 testnet will be set up on May 18th.
> 
> is that the final or we will see RC3?

We will see RC3 in a month. And then Neo v3.0.0 Testnet.

**Comment by Gimchinam** [comment]
Is mainnet 3.0 available around June??

**Comment by Ethour** [comment]
@superboyiii which is the difference between RCxx release and Neo v3.0.0 testnet? I assumed that RCxx was altrady a testnet, isn't it?

**Comment by superboyiii** [comment]
RC2 Testnet set up complete.

**Comment by superboyiii** [comment]
> @superboyiii which is the difference between RCxx release and Neo v3.0.0 testnet? I assumed that RCxx was already a testnet, isn't it?

Difference is data will be reset in Neo v3.0.0 testnet and then will never be reset again.

**Comment by devhawk** [comment]
@superboyiii Can we create a RC3 issue since we have finished RC2?
