### ISSUE TITLE
Neo v3.0.0 Checklist

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2519]
Now We're making the checklist of neo v3.0.0 for release preparation. We plan to release v3.0.0 in the middle of July and then testnet will be launched. There will be a data reset on v3.0.0 testnet and then no reset any more. We plan to run Testnet for several weeks to ensure it's stable enough and then Mainnet will be launched. Most of the PRs on this checklist has been solved or nearly to be merged. Additional tasks collection will be accepted only if it's necessary.

**Mandatory issues**

- [x] Different network fee calculation https://github.com/neo-project/neo/issues/2501

**Mandatory PRs**

- [x] Fix calculate network fee https://github.com/neo-project/neo/pull/2497
- [x] add new OracleResponseCode:ContentTypeNotSupported  https://github.com/neo-project/neo/pull/2505
- [x] Fix gaslimit https://github.com/neo-project/neo/pull/2493
- [x] Add new syscall: System.Runtime.GetNetwork https://github.com/neo-project/neo/pull/2515
- [x] Add random number to neo https://github.com/neo-project/neo/pull/2477
- [x] add null filter in JsonPath https://github.com/neo-project/neo/pull/2518
- [x] Add ContentTypeNotSupported OracleResponseCode https://github.com/neo-project/neo-modules/pull/599
- [x] Fix StackItemFromJson https://github.com/neo-project/neo-modules/pull/598
- [x] Fix json properties https://github.com/neo-project/neo-modules/pull/593
- [x] Fix gaslimit https://github.com/neo-project/neo-modules/pull/604
- [x] add Nonce to Block, add Random to Runtime https://github.com/neo-project/neo-devpack-dotnet/pull/648
- [x] Fix oracle https://github.com/neo-project/neo-modules/pull/608
- [x] Add Random number to N3 https://github.com/neo-project/neo-modules/pull/596
- [x] Fix calnetfee https://github.com/neo-project/neo/pull/2520
- [x] Optimize GetHashCode https://github.com/neo-project/neo-vm/pull/417
- [x] struct equal limit https://github.com/neo-project/neo-vm/pull/428
- [x] FIX SQRT https://github.com/neo-project/neo-vm/pull/427
- [x] Fix clone struct https://github.com/neo-project/neo-vm/pull/423
- [x] FIX SQRT PRICE https://github.com/neo-project/neo/pull/2540
- [x] Fix BinaryDeserialize https://github.com/neo-project/neo/pull/2531
- [x] OSX compatible https://github.com/neo-project/neo/pull/2511
- [x] Murmur128: process data in Little-Endian fashion https://github.com/neo-project/neo/pull/2541
- [x] Change Initialize GAS to 52000000 * Factor https://github.com/neo-project/neo/pull/2544

@neo-project/developers @neo-project/core @neo-project/ngd-seattle

**Comment by csmuller** [comment]
@superboyiii, PR #2497 is only a partial fix to the issues with calculatenetworkfee. What about #2501?

**Comment by superboyiii** [comment]
> @superboyiii, PR #2497 is only a partial fix to the issues with calculatenetworkfee. What about #2501?

We'll push a PR to fix it soon. Added to checklist.

**Comment by devhawk** [comment]
Runtime.Network (i.e. https://github.com/neo-project/neo/pull/2515) also needs to be added to devpack. Probably can be done as part of https://github.com/neo-project/neo-devpack-dotnet/pull/648

**Comment by devhawk** [comment]
Final decision about https://github.com/neo-project/neo/pull/2425 should be on this list

**Comment by superboyiii** [comment]
> Final decision about #2425 should be on this list

We plan to implement current neo-go solution(notary) when mainnet launched. C# version need more time to test for details.

**Comment by roman-khimov** [comment]
#2536, #2534, neo-project/neo-vm#418 seem to be release-critical to be. Worth considering: neo-project/neo-vm#421 (it's hard to change it afterwards).

**Comment by superboyiii** [comment]
> #2536, #2534, [neo-project/neo-vm#418](https://github.com/neo-project/neo-vm/issues/418) seem to be release-critical to me. Worth considering: [neo-project/neo-vm#421](https://github.com/neo-project/neo-vm/issues/421) (it's hard to change it afterwards).

All added

**Comment by roman-khimov** [comment]
Please also add #2541, current Murmur implementation is non-standard which will lead to interoperability issues between various node implementations.

**Comment by ioannistsil** [comment]
@superboyiii all merged update checklist please :)

**Comment by superboyiii** [comment]
Mainnet launched. Neo to the moon! 🥳
