### ISSUE TITLE
Neo v3.0.3 Checklist

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2601]
Now We're making the checklist of neo v3.0.3 for release preparation. We plan to release v3.0.3 in two weeks and then upgrade testnet and mainnet. It's a hotfix version, these core issues and PRs are included. 

**Mandatory issues**

- [x] CountedGroups and CountedContracts witness scopes https://github.com/neo-project/neo/issues/2583 (will be fixed after v3.0.3)

**Mandatory PRs**

- [x] Clone item when commit https://github.com/neo-project/neo/pull/2573
- [x] Fix CheckWitness for WitnessScope.CustomGroups https://github.com/neo-project/neo/pull/2586
- [x] add new witness scope https://github.com/neo-project/neo/pull/2596 (will be fixed after v3.0.3)
- [x] [StateService] Allow value empty https://github.com/neo-project/neo-modules/pull/634
- [x] [StateService] get historical state https://github.com/neo-project/neo-modules/pull/638
- [x] Check null in native contracts https://github.com/neo-project/neo/pull/2610
- [x] Add manifest classes https://github.com/neo-project/neo-devpack-dotnet/pull/670
- [x] RpcClient missing state root related methods https://github.com/neo-project/neo-modules/pull/644

@neo-project/developers @neo-project/core @neo-project/ngd-seattle

**Comment by devhawk** [comment]
https://github.com/neo-project/neo-modules/issues/202

Can we ship oracles and state service plugins on nuget along with RpcClient, RpcServer and Consensus plugins?

**Comment by devhawk** [comment]
Also, need to update neo package reference in neo modules to latest neo version: https://github.com/neo-project/neo-modules/issues/643

**Comment by devhawk** [comment]
https://github.com/neo-project/neo-modules/issues/635 should be on this list

**Comment by superboyiii** [comment]
> [neo-project/neo-modules#202](https://github.com/neo-project/neo-modules/issues/202)
> 
> Can we ship oracles and state service plugins on nuget along with RpcClient, RpcServer and Consensus plugins?

I think they should be there.

**Comment by superboyiii** [comment]
> [neo-project/neo-modules#635](https://github.com/neo-project/neo-modules/issues/635) should be on this list

Not much time left, we'll add these in the version after next.

**Comment by devhawk** [comment]
> > [neo-project/neo-modules#635](https://github.com/neo-project/neo-modules/issues/635) should be on this list
> 
> Not much time left, we'll add these in the version after next. We'd like to hotfix #2573 ASAP this week.

As long as https://github.com/neo-project/neo-modules/pull/638 is in 3.0.3, I can get by w/o a fix for https://github.com/neo-project/neo-modules/issues/635

**Comment by superboyiii** [comment]
> w/o

Merged.

**Comment by gsmachado** [comment]
Any expected date for the upcoming release? 😄 😅

**Comment by superboyiii** [comment]
> Any expected date for the upcoming release? 😄 😅

https://github.com/neo-project/neo-node/releases/tag/v3.0.3
