### ISSUE TITLE
Neo v3.1.0 Checklist

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2620]
Now We're making the checklist of neo v3.0.4 for release preparation. We plan to release v3.0.4 in two weeks and then upgrade testnet and mainnet. It's a hotfix and enhancement version, these core issues and PRs are included. 

**Mandatory issues**

~~NCCS raises nullable context error https://github.com/neo-project/neo-devpack-dotnet/issues/684~~ (Need further discussion)
- [x] CountedGroups and CountedContracts witness scopes https://github.com/neo-project/neo/issues/2583 
- [x] Nep11 Tracker https://github.com/neo-project/neo-modules/issues/542
- [x] independent MPTTrie classes https://github.com/neo-project/neo-modules/issues/648
- [x] nccs compiles contract that won't deploy https://github.com/neo-project/neo-devpack-dotnet/issues/657

**Mandatory PRs**

~~add new witness scope https://github.com/neo-project/neo/pull/2596~~ (replaced by https://github.com/neo-project/neo/pull/2622)
~~Set nullableContextOptions https://github.com/neo-project/neo-devpack-dotnet/pull/687~~ (Need further discussion) 
- [x] Add new WitnessScope: Rules https://github.com/neo-project/neo/pull/2622
- [x] Validate manifest after compilation https://github.com/neo-project/neo-devpack-dotnet/pull/658
- [x] Add token tracker https://github.com/neo-project/neo-modules/pull/671
- [x] mpt project https://github.com/neo-project/neo-modules/pull/658
- [x] Strict supportedstandards https://github.com/neo-project/proposals/pull/143
- [x] .NET 6.0 https://github.com/neo-project/neo-node/pull/838
- [x] .NET 6.0 https://github.com/neo-project/neo-modules/pull/673
- [x] Add data parameter when deploy and update contract https://github.com/neo-project/neo-node/pull/837
- [x] Fix FS Dispose Error https://github.com/neo-project/neo-modules/pull/675

@neo-project/developers @neo-project/core @neo-project/ngd-seattle

**Comment by devhawk** [comment]
Can we add https://github.com/neo-project/neo-modules/pull/658?

**Comment by superboyiii** [comment]
> Can we add [neo-project/neo-modules#658](https://github.com/neo-project/neo-modules/pull/658)?

Added

**Comment by csmuller** [comment]
Just stumbled over https://github.com/neo-project/neo-vm/pull/443. Should that go into 3.1.0?

**Comment by superboyiii** [comment]
> Just stumbled over [neo-project/neo-vm#443](https://github.com/neo-project/neo-vm/pull/443). Should that go into 3.1.0?

Already included.
![1637056792(1)](https://user-images.githubusercontent.com/38493437/141964066-4538976f-22b7-4da8-bfd9-8d887183f083.png)

**Comment by superboyiii** [comment]
https://github.com/neo-project/neo-node/releases/tag/v3.1.0
