### ISSUE TITLE
Neo v3.3.0 Checklist

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2715]
Now We're making the checklist of neo v3.3.0 for release preparation. We plan to release v3.3.0 and then upgrade testnet and mainnet. It's a hotfix version which should be applied on testnet **ASAP**.

**Mandatory issues**
- [x] GAS price for CreateMultisigAccount https://github.com/neo-project/neo/issues/2710
- [x] Committee can be smaller than CommitteeMembersCount https://github.com/neo-project/neo/issues/2706
- [x] GetTransactionSigners method of native Ledger should check for transaction traceability https://github.com/neo-project/neo/issues/2698
- [x] TransactionState.FromStackItem throws when state not available https://github.com/neo-project/neo/issues/2721
- [x] Is the conversion of transaction signer to stackitem implemented as intended?https://github.com/neo-project/neo/issues/2705

**Mandatory PRs**
- [x] Sync GetTransactionSigners https://github.com/neo-project/neo-devpack-dotnet/pull/731
- [x] Fix fee of CreateMultisigAccount https://github.com/neo-project/neo/pull/2712
- [x] NEP6Wallet.ToJson method (and tests) https://github.com/neo-project/neo/pull/2714
- [x] Fix Signer.ToStackItem() https://github.com/neo-project/neo/pull/2711
- [x] Fix committe issue https://github.com/neo-project/neo/pull/2707
- [x] Add traceable to GetTransactionSigners https://github.com/neo-project/neo/pull/2703
- [x] Fix UpdateCounter issues https://github.com/neo-project/neo/pull/2697
- [x] limit the maximum equal comparison  https://github.com/neo-project/neo-vm/pull/454
- [x] fix lower for TR region https://github.com/neo-project/neo-modules/pull/712
- [x] Add new opcodes: MODMUL and MODPOW https://github.com/neo-project/neo-vm/pull/455
- [x] Sync NeoVM: add MODMUL and MODPOW https://github.com/neo-project/neo/pull/2719
- [x] Fix fee of CreateMultisigAccount https://github.com/neo-project/neo/pull/2712
- [x] Snapshot isolation https://github.com/neo-project/neo/pull/2729
- [x] Optimize Buffer  https://github.com/neo-project/neo-vm/pull/470

@neo-project/core @neo-project/developers @neo-project/ngd-seattle

**Comment by Liaojinghui** [comment]
the issue for pr #2703 is #2698 instead of #2709

**Comment by dusmart** [comment]
IMO, this [commit](https://github.com/neo-project/neo-vm/pull/454) in neo-vm is also important.

**Comment by devhawk** [comment]
Can we consider https://github.com/neo-project/neo-modules/issues/711 for 3.2.2?

**Comment by roman-khimov** [comment]
Is neo-project/neo-vm#455 also a part of 3.2.2 now?

**Comment by superboyiii** [comment]
> Is [neo-project/neo-vm#455](https://github.com/neo-project/neo-vm/pull/455) also a part of 3.2.2 now?

Done

**Comment by superboyiii** [comment]
> Can we consider [neo-project/neo-modules#711](https://github.com/neo-project/neo-modules/issues/711) for 3.2.2?

Sure

**Comment by devhawk** [comment]
I think we will hit https://github.com/neo-project/neo/issues/2721 when we go to upgrade testnet to 3.2. I'm guessing we should include #2721 in this checklist.

**Comment by devhawk** [comment]
Where are we on shipping 3.3 version of dotnet devpack?

**Comment by superboyiii** [comment]
https://github.com/neo-project/neo-node/releases/tag/v3.3.0
