### ISSUE TITLE
Neo v3.3.1 Checklist

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2770]
Now We're making the checklist of neo v3.3.1 for release preparation. We plan to release v3.3.1 in 2 days and then upgrade both testnet and mainnet. It's a hotfix version which should be applied **ASAP**.

**Mandatory issues**
- [x] Presssure test on v3.3.0 cause execution failed https://github.com/neo-project/neo-vm/issues/477
- [x] v3.3.0 need more than 30 hours for syncing mainnet  https://github.com/neo-project/neo-vm/issues/481
- [x] Native contract state can possibly be dependant on culture https://github.com/neo-project/neo/issues/2766

**Mandatory PRs**
- [x] Thread safe static items (v2) https://github.com/neo-project/neo-vm/pull/480
- [x] Optimize DebuggerDisplay https://github.com/neo-project/neo-vm/pull/484
- [x] Track CompoundType and Buffer only https://github.com/neo-project/neo-vm/pull/486
- [x] ReadNullableArray missing ref https://github.com/neo-project/neo/pull/2769
- [x] Fix native contract ABI order https://github.com/neo-project/neo/pull/2768
- [x] delete plugin folder when uninstall plugin https://github.com/neo-project/neo-node/pull/860
- [x] minimal recovery message from f to f+1 https://github.com/neo-project/neo-modules/pull/723
- [x] Rpc Client iterators https://github.com/neo-project/neo-modules/pull/721
- [x] Allow traverse iterators https://github.com/neo-project/neo-modules/pull/715
- [x] RpcClient.InvokeScriptAsync doesn't accept Script param https://github.com/neo-project/neo-modules/pull/732

@neo-project/core @neo-project/developers @neo-project/ngd-seattle

**Comment by devhawk** [comment]
Since we haven't shipped neo-modules 3.3.1 yet, can we consider https://github.com/neo-project/neo-modules/pull/732? It's a minor parameter type change to enable better compatibility with `Script` changes made in https://github.com/neo-project/neo-vm/pull/466

**Comment by superboyiii** [comment]
> Since we haven't shipped neo-modules 3.3.1 yet, can we consider [neo-project/neo-modules#732](https://github.com/neo-project/neo-modules/pull/732)? It's a minor parameter type change to enable better compatibility with `Script` changes made in [neo-project/neo-vm#466](https://github.com/neo-project/neo-vm/pull/466)

Sure. Included.

**Comment by superboyiii** [comment]
https://github.com/neo-project/neo-node/releases/tag/v3.3.1
https://github.com/neo-project/neo-modules/releases/tag/v3.3.1
