### ISSUE TITLE
Neo-VM migration checklist

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2972]
**Summary or problem description**
The initiative to unify our repositories is underway, starting with the Neo-VM. We've encountered a range of unpredicted challenges during this process. This issue was created to facilitate the planning of the migration, since there are multiple tasks to be done, on different stages.

**Do you have any solution you want to propose?**
We need to break down the migration into smaller issues, so it can be discussed properly.

Step 1: Initial migration (files)
- [X] Migrate the .csproj files and source files (#2970 )
- [X] Configure the VM project to reuse metadata information from the Directory.Build.props file (#2970)
  - [x] Update Directory.Build.props to use the `TargetFrameworks` property  (#2989)
- [X] Update the build workflow to support the Neo-VM project (no changes required)

Step 2: Improvements
- [x] #2971 

Removed from scope:
- #2973 
 

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- VM

**Comment by cschuchardt88** [comment]
> Update the build workflow to support the Neo-VM project

This maybe already done for us.  At least for release. 

Uses solution file in repo
https://github.com/neo-project/neo/blob/61a066583eef53c8eb7b770dcc3deb0305ab11db/.github/workflows/main.yml#L91-L93

**Comment by lock9** [comment]
Yes, I've double checked and the tests are being run correctly.
