### ISSUE TITLE
[V3.7.5 Checklist] This is a checklist for version 3.7.5 hotfix

### ISSUE THREAD

**Issue by Jim8y** [neo-project/neo#3321]
**Summary or problem description**
3.7.5 is a hotfix that will only contain bug fixes.

> **Warning**
> 
> **Hardfork required.**

- [x] https://github.com/neo-project/neo/pull/3261
- [x] https://github.com/neo-project/neo/pull/3263
- [x] https://github.com/neo-project/neo/pull/3282
- [x] https://github.com/neo-project/neo/pull/3290
- [x] https://github.com/neo-project/neo/pull/3299
- [x] https://github.com/neo-project/neo/pull/3301

**Comment by NGDAdmin** [comment]
We need a v3.7.5 branch which based on v3.7.4 tag and we need temporarily cancel read-only for neo-modules to make new release available.
@shargon

**Comment by cschuchardt88** [comment]
For release to work we need #3320 #3306 in `.github` workflow actions

**Comment by Jim8y** [comment]
> For release to work we need #3320 #3306 for `.github` workflow actions

But how 3.7.4 was released? 3.7.5 will purely based on 3.7.4.

**Comment by cschuchardt88** [comment]
> > For release to work we need #3320 #3306 for `.github` workflow actions
> 
> But how 3.7.4 was released? 3.7.5 will purely based on 3.7.4.

Nevermind than

**Comment by superboyiii** [comment]
Please add https://github.com/neo-project/neo/pull/3261, although it will be merged to https://github.com/neo-project/neo-modules.git

**Comment by superboyiii** [comment]
Maybe remove https://github.com/neo-project/neo/pull/3306, it doesn't matter v3.7.4.

**Comment by cschuchardt88** [comment]
Add #3322

**Comment by cschuchardt88** [comment]
> > For release to work we need #3320 #3306 for `.github` workflow actions
> 
> But how 3.7.4 was released? 3.7.5 will purely based on 3.7.4.

I take back what i said. It was released on `neo-modules` repo?

**Comment by superboyiii** [comment]
> > > For release to work we need #3320 #3306 for `.github` workflow actions
> > 
> > 
> > But how 3.7.4 was released? 3.7.5 will purely based on 3.7.4.
> 
> I take back what i said. It was released on `neo-modules` repo?

Yes
