### ISSUE TITLE
Neo3-preview1 release checklist

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#977]
**Neo3-preview1 release checklist**
Checklist of tasks required to be accomplished for neo3-preview1.
This release should be concluded by **16/08/2019** (delayed).

**Mandatory issues**
- [x] Finish scoped witnesses (#544)
- [x] Add readonly methods to the ABI (#927)
- [x] Limit the size of the block to 256KB (#953)
- [x] Update neo-cli to support scoped witnesses (#544)
- [x] Remove Simple Policy plugin ([neo-plugins](https://github.com/neo-project/neo-plugins/pull/110), @vncoelho)

**Testing guide**
- [x] Consensus with 7 nodes
- [x] Send neo to account
- [x] Test auto-claimable gas
- [x] Send gas to account
- [x] Send neo to account using multisig
- [x] Send neo to account using multisig
- [x] Send gas to contract
- [x] Send neo to contract
- [x] Retrieve gas from contract using single signature
- [x] Retrieve gas from contract using multisig
- [x] Retrieve neo from contract using single signature
- [x] Retrieve gas from contract using multisig

**Postponed to preview2**:
- Finish NetworkFee update (#840, #979)
- Create a NEP-5 template (#973, @belane)
- Update neon compiler to accept read-only methods (https://github.com/neo-project/neo-devpack-dotnet/pull/93)
- Compile NEP-5 template 
- Upload NEP-5 SmartContract example
- Test all NEP-5 SmartContract methods

Tests:
- Test Scoped witness with global witness scope
- Test Scoped witness with scripthash scope, single use
- Test Scoped witness with scripthash scope, multiple uses
- Test Scoped witness with multisig, single use
- Test Scoped witness with multisig, multiple uses

**Comment by lock9** [comment]
@neo-project/core  I kindly ask you to evaluate this

**Comment by igormcoelho** [comment]
Very good idea! Congratulations

**Comment by superboyiii** [comment]
Send neo to account: It works when sending from the Genesis multisig address. It will fail when sending from a no-gas-inside address because of system fee.
Send gas to account: It doesn't work at all since system fee is still necessary in current logic.
Test auto-claimable gas: It works.
Further tests aren't able to go on until these issues are solved.
![image](https://user-images.githubusercontent.com/38493437/62352530-f387ba80-b53a-11e9-9069-d2301f01c4b1.png)

**Comment by erikzhang** [comment]
> It will fail when sending from a no-gas-inside address because of system fee.

This is as expected. Transfers require a fee.

**Comment by lock9** [comment]
@superboyiii  do you want to add some extra tests you plan to do in here?
For instance: transfer with fee, transfer without fee, etc. 
I think all free tx will be dropped in neo3, but we need to ensure that people without NEO can start using the chain (paid by 3rd party). Otherwise, all people will need an exchange account to start using neo. Definitely not good.

**Comment by shargon** [comment]
Someone is doing these tests?

**Comment by superboyiii** [comment]
@shargon Hi, Shargon, I've tried these below: 
Send neo to account(work well)
  Test auto-claimable gas(work well)
  Send gas to account(work well)
  Send neo to account using multisig(work well)
  Send neo to account using multisig(work well)
  Compile NEP-5 template(fail because of incomplete neon complier)
  Send gas to contract(work well)
  Send neo to contract(work well)
  Retrieve gas from contract using single signature(work well)
  Retrieve gas from contract using multisig(work well)
  Retrieve neo from contract using single signature(work well)
  Retrieve gas from contract using multisig(work well)

**Comment by superboyiii** [comment]
@lock9  Dute to my test result, fee is necessary now. No gas no tx. It's reasonable but we'd better not make ```Fee``` as ```ceil()``` in next improvement.

**Comment by shargon** [comment]
@superboyiii Thanks for the summary!

**Comment by shargon** [comment]
> It's reasonable but we'd better not make net_fee as ceil()

Could you open a issue about this?

**Comment by superboyiii** [comment]
Sure.

**Comment by superboyiii** [comment]
https://github.com/neo-project/neo/issues/1051

**Comment by superboyiii** [comment]
![image](https://user-images.githubusercontent.com/38493437/63746919-756bc900-c8d8-11e9-8e06-13512bf3f6d9.png)
Consensus with 7 nodes works well.
