### ISSUE TITLE
NEO 3 RPC Update List

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#996]
This is a checklist for updates in our RPC features. This list is based on previous issues and comments (I will try to list them here when possible).
I believe this will remain open until NEO 3 is officially released.

REST update (#726) :
- [ ] Create swagger documentation (#1003)
- [ ] Add REST uri endpoints (#1004 )
- [ ] Update error messages (#975)
- [ ] Update SDK to use REST API
- [ ] Add REST API section to the documentation

GraphQL update (#623) :
- [ ] Create GraphQL schema
- [ ] Update data serialization methods
- [ ] Add GraphQL endpoint
- [ ] Update SDK to support GraphQL
- [ ] Add GraphQL section to the documentation

**Comment by Jarbas666** [comment]
Nice thing about this.

**Comment by Tommo-L** [comment]
Can we implement them in NEO3, and also the SPV?

**Comment by lock9** [comment]
@Tommo-L  is the SPV something provided using RPC? We need MPT before this is implemented, right?

**Comment by Tommo-L** [comment]
> Is the SPV something provided using RPC? We need MPT before this is implemented, right?

Yes

**Comment by wanglongfei88** [comment]
@lock9  we are going to keep both RPC and REST, right ?

**Comment by lock9** [comment]
Hi!
I think so, I consider REST very important if we expect to onboard “web” developers (both frontend and backend)

**Comment by wanglongfei88** [comment]
> Hi! I think so, I consider REST very important if we expect to onboard “web” developers (both frontend and backend)

I agree. I think it is good for us to provide both options. And I see this  "Update SDK to use REST API" in the list. Do you mean SDK to support both, or update SDK to only use REST?
